### ISSUE TITLE
environment.py raises deprecation warnings

### ISSUE THREAD

**Issue by j-wags** [openforcefield/openff-toolkit#145] opened 2018-12-07 20:33 UTC
I've been working on a build of openforcefield that I built on miniconda in October 2018. Whenever `environments.py` is imported, I get a few deprecation warnings that appear, probably related to regex parsing.

```
=============================== warnings summary ===============================
<unknown>:64: DeprecationWarning: invalid escape sequence \C

<unknown>:65: DeprecationWarning: invalid escape sequence \C

<unknown>:67: DeprecationWarning: invalid escape sequence \C

<unknown>:113: DeprecationWarning: invalid escape sequence \C

<unknown>:114: DeprecationWarning: invalid escape sequence \F

<unknown>:185: DeprecationWarning: invalid escape sequence \C

<unknown>:187: DeprecationWarning: invalid escape sequence \F

<unknown>:387: DeprecationWarning: invalid escape sequence \C

<unknown>:432: DeprecationWarning: invalid escape sequence \C

<unknown>:433: DeprecationWarning: invalid escape sequence \C

<unknown>:435: DeprecationWarning: invalid escape sequence \C

<unknown>:483: DeprecationWarning: invalid escape sequence \C

<unknown>:484: DeprecationWarning: invalid escape sequence \[

<unknown>:550: DeprecationWarning: invalid escape sequence \C

<unknown>:551: DeprecationWarning: invalid escape sequence \[

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:51: DeprecationWarning: invalid escape sequence \(
  """

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:85: DeprecationWarning: invalid escape sequence \[
  atom, a_in, a_out = _find_embedded_brackets(smirks, '\[', '\]')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:85: DeprecationWarning: invalid escape sequence \]
  atom, a_in, a_out = _find_embedded_brackets(smirks, '\[', '\]')

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:89: DeprecationWarning: invalid escape sequence \[
  atom, temp_in, temp_out = _find_embedded_brackets(smirks[a_out+1:], '\[', '\]')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:89: DeprecationWarning: invalid escape sequence \]
  atom, temp_in, temp_out = _find_embedded_brackets(smirks[a_out+1:], '\[', '\]')

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:107: DeprecationWarning: invalid escape sequence \(
  embedded, p_in, p_out = _find_embedded_brackets(atom, '\(', '\)')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:107: DeprecationWarning: invalid escape sequence \)
  embedded, p_in, p_out = _find_embedded_brackets(atom, '\(', '\)')

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:111: DeprecationWarning: invalid escape sequence \[
  first, f_in, f_out = _find_embedded_brackets(embedded, '\[','\]')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:111: DeprecationWarning: invalid escape sequence \]
  first, f_in, f_out = _find_embedded_brackets(embedded, '\[','\]')

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:273: DeprecationWarning: invalid escape sequence \[
  sub_string, start, end = _find_embedded_brackets(smirks, '\[','\]')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:273: DeprecationWarning: invalid escape sequence \]
  sub_string, start, end = _find_embedded_brackets(smirks, '\[','\]')

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:475: DeprecationWarning: invalid escape sequence \d
  element_num = "!?[#]\d+"

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:481: DeprecationWarning: invalid escape sequence \$
  replace_str = "\$\w+"

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:485: DeprecationWarning: invalid escape sequence \d
  needs_int = "!?[DHjrVX^]\d+"

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:487: DeprecationWarning: invalid escape sequence \d
  optional_int = "!?[Rx+-]\d*"

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:489: DeprecationWarning: invalid escape sequence \d
  chirality = "!?[@]\d+|!?[@]@?"

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:622: DeprecationWarning: invalid escape sequence \[
  atom_string, start, end = _find_embedded_brackets(smirks, '\[', '\]')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:622: DeprecationWarning: invalid escape sequence \]
  atom_string, start, end = _find_embedded_brackets(smirks, '\[', '\]')

/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:674: DeprecationWarning: invalid escape sequence \[
  atom_string, start, end = _find_embedded_brackets(leftover, '\[', '\]')
/Users/jeffreywagner/projects/OpenFF/2018_10_09_topology_implementation/openforcefield/openforcefield/typing/chemistry/environment.py:674: DeprecationWarning: invalid escape sequence \]
  atom_string, start, end = _find_embedded_brackets(leftover, '\[', '\]')

```

**Comment by j-wags** [comment] 2019-03-11 17:59
I am unable to reproduce these warning messages now, however I don't see any code changes in the git history that would have fixed this issue. Would be interested to know if anyone else encounters this behavior.

**Comment by bannanc** [comment] 2019-03-11 22:28
Oh I have encountered these also, I have them in an issue tracker on chemper too. I've been planning on looking into. I somehow missed this assignment, sorry it hasn't  been addressed sooner.

**Comment by bannanc** [comment] 2019-03-11 22:29
The only thing I can think is that it is a regex version change, but I haven't had time to see how they're handling it.

**Comment by davidlmobley** [comment] 2019-03-27 22:03
@bannanc do you have a use case which triggers this, since Jeff says he doesn't see them anymore?

**Comment by andrrizzi** [comment] 2019-03-28 09:15
I fixed a lot of those warnings in #212 . Transforming SMILES strings into literal strings (i.e. prepending `r` as in `r'CCC'`) solves the issue, but I haven't closed this yet because I think there are a few left. I didn't do a systematic search.

**Comment by bannanc** [comment] 2019-04-01 20:01
Thanks @andrrizzi! 
@davidlmobley and @j-wags it looks like Andrea fixed this a while ago, I probably have an out dated version in ChemPer, I've been waiting for `Openforcefield` version 1.0.0 before I make it a dependency.

**Comment by j-wags** [comment] 2019-04-01 20:06
@bannanc - @andrrizzi and I were actually just triaging which examples to bring back online, and were going to ask about what to do with `openforcefield/examples/chemicalEnvironments`. Do we want the ChemicalEnvironment code to live in the OFF toolkit or in ChemPer? Maybe we could chat today.

**Comment by jchodera** [comment] 2019-04-01 23:18
I think we currently use the chemical environments code to validate whether labeled SMIRKS describe an atom, bond, angle, or torsion.

**Comment by bannanc** [comment] 2019-04-01 23:33
Yes, you do, so if we permanently move it out of `openforcefield` and into `chemper` then you have to make `chemper` a dependency, I'm not sure that makes sense in the long term or right now... Either way, I don't think we need the examples for how to use it here. I could move those examples to ChemPer where users are probably digging in because they're thinking about how to change SMIRKS patterns with a python API. 

I'd always planned on making `openforcefield` a dependency of `chemper` at some point to get access to `environment.py`, but also to make examples where you make SMIRKS patterns and put them into `offxml` files and/or `forcefield` objects.

**Comment by mattwthompson** [comment] 2022-07-07 14:48
I'm unaware of all of the history here, but I can't reproduce what I believe the original issue was:


```python3
>>> from openff.toolkit import __version__
>>> __version__
'0.11.0rc2+2.g8fd71fc7'
>>> from openff.toolkit.typing.chemistry.environment import *
>>>
```

If I'm incorrect, please re-open or file a new issue.

**Closed by mattwthompson** 2022-07-07 14:48 UTC
