### ISSUE TITLE
Incorrect v-site orientation

### ISSUE THREAD

**Issue by SimonBoothroyd** [openforcefield/openff-toolkit#1159] opened 2021-12-21 14:02 UTC
**Describe the bug**

The toolkit currently by default sorts the list of parent atom indices when creating a v-site which leads to different orientations for the v-site than were expected.

Presumably this will lead to v-sites being displaced in the wrong direction. 

**To Reproduce**

```
from openff.toolkit.typing.engines.smirnoff import ForceField
from openmm import unit

force_field = ForceField()

vsite_handler = force_field.get_parameter_handler("VirtualSites")
vsite_handler.add_parameter(
    parameter_kwargs={
        "smirks": "[#6:2]=[#8:1]",
        "name": "EP",
        "type": "BondCharge",
        "distance": 0.7 * unit.nanometers,
        "match": "once",
        "charge_increment1": 0.2 * unit.elementary_charge,
        "charge_increment2": 0.1 * unit.elementary_charge,
        "sigma": 1.0 * unit.angstrom,
        "epsilon": 2.0 / 4.184 * unit.kilocalorie_per_mole,
    }
)

from openff.toolkit.topology import Molecule
molecule = Molecule.from_mapped_smiles("[O:2]=[C:1]=[O:3]")

from openmm import System
omm_system: System
omm_system, topology = force_field.create_openmm_system(
    molecule.to_topology(), return_topology=True
)

for molecule in topology.reference_molecules:
    for v_site in molecule.virtual_sites:
        for particle in v_site.particles:
            print(particle.orientation)

for i in range(omm_system.getNumParticles()):

    if not omm_system.isVirtualSite(i):
        continue

    omm_v_site = omm_system.getVirtualSite(i)

    print(
        tuple(omm_v_site.getParticle(j) for j in range(omm_v_site.getNumParticles()))
    )
```

**Output**

_Actual_

```
(0, 1)
(0, 2)
(0, 1)
(0, 2)
```

_Expected_

```
(1, 0)
(2, 0)
(1, 0)
(2, 0)
```

**Computing environment (please complete the following information):**
 - Operating system
 - Output of running `conda list`   `openff-toolkit = 0.10.1`

**Additional context**

**Comment by SimonBoothroyd** [comment] 2021-12-21 14:04
[This is the line that sorts the atom indices](https://github.com/openforcefield/openff-toolkit/blob/192fe7f1c5b49033ebc2c2ca49aea5e10d2b6b89/openff/toolkit/typing/engines/smirnoff/parameters.py#L5175)

**Comment by j-wags** [comment] 2021-12-21 16:00
Yup. I can confirm that this is broken. The vsite implementation in the code is really complex (as hinted at by the big comment right by the line you linked), so I'm working on figuring out a path forward here. @trevorgokey, do you have any thoughts on this?

**Comment by j-wags** [comment] 2021-12-21 16:30
There may be a more general concept here, but I'm failing to think of it, so I'm trying to wrap my head around a smaller question: Is there a reasonable case where a `BondChargeVirtualSite` SHOULD have different behavior for `match="once"` versus `match="all_permutations"`? 

If not, AND if this issue only affects `BondChargeVirtualSites` we could just skip this sort for BCVSs, or only allow one value of the `match`attribute for them.

**Comment by trevorgokey** [comment] 2021-12-21 16:30
I can double check this, but I remember noting that we took [the opinion](https://github.com/openforcefield/openff-toolkit/blob/master/openff/toolkit/typing/engines/smirnoff/parameters.py#L5728) that we cannot/do not track any correspondence between our indices and OpenMM indices, since going to OpenMM was considered a 1-way operation. Before actually checking, it may be the case that the displacements used with the given orders are correct.

Also, I have eyes on the fact that a mapped SMILES was used, and the OpenMM indices are out of `ValenceDict` order, so there is probably some complexity to untangle here. How do we handle indices when mapped SMILES are exported to OpenMM?

**Comment by trevorgokey** [comment] 2021-12-21 16:32
> Is there a reasonable case where a BondChargeVirtualSite SHOULD have different behavior for match="once" versus match="all_permutations"?
Molecules like O_2 come to mind here

**Comment by j-wags** [comment] 2021-12-21 16:34
Hm, would an O2 with only one BCVS make sense though? I don't think that we need to support asymmetric O2 (it wouldn't be "reasonable").

**Comment by trevorgokey** [comment] 2021-12-21 16:37
Yes we likely don't, but we don't know if a SMIRKS is completely symmetric so I am not sure how you would detect when to enforce such symmetry constraints

**Comment by trevorgokey** [comment] 2021-12-21 16:40
Also, FWIW, the key is sorted because it is related to the `first` permutation/key of the given key, which I use to design the displacements. If it is not sorted, I suspect geometries will be incorrect since otherwise they can be manipulated with SMARTS mapping. But, I'll still need to dig in to check if the above example is working correctly.

**Comment by trevorgokey** [comment] 2021-12-21 16:41
It is also might be the case that I did not consider mapped SMILES, and this is causing some issues that need to be fixed.

**Comment by j-wags** [comment] 2021-12-21 16:46
I doubt that it's due to creating the molecule from a mapped SMILES. After running `Molecule.from_mapped_smiles`, the output is completely identical to what could be achieved using `Molecule.add_atom` and `add_bond`, but there could be some subtlety here so feel free to take a look. I think this may just be exercising a case or atom ordering that we hadn't considered. 

I did a little confirmation experiment using the vsite showcase notebook - I'll summarize that in a minute.

**Comment by j-wags** [comment] 2021-12-21 16:55
Modifying the XML in the [vsite_showcase notebook](https://github.com/openforcefield/openff-toolkit/blob/192fe7f1c5b49033ebc2c2ca49aea5e10d2b6b89/examples/virtual_sites/vsite_showcase.ipynb), specifically for the `C-Cl` BondChargeVirtualSite:

With `match=once`, in an order that should put the vsite INSIDE the C, we get the CORRECT placement.
```
            type="BondCharge"
            name="EPCl"
            smirks="[*:1][Cl:2]"
            match="once"
```
![Screen Shot 2021-12-21 at 8 47 27 AM](https://user-images.githubusercontent.com/16329175/146967742-e5ebfc21-3cef-4f9a-bc66-22dfa916d133.png)


With `match=once`, in an order that should put the vsite OUTSIDE the Cl, we INCORRECTLY get the vsite inside the C (not sure why the bonds are drawn to the vsite in this case)
```
            type="BondCharge"
            name="EPCl"
            smirks="[*:2][Cl:1]"
            match="once"
```
![Screen Shot 2021-12-21 at 8 46 35 AM](https://user-images.githubusercontent.com/16329175/146967417-006f33ae-f914-4ed4-8c5c-85ec8d63693c.png)



Now doing the same two as above, but with `match="all_permutations"`, we get the CORRECT behavior in both cases:


```
            type="BondCharge"
            name="EPCl"
            smirks="[*:2][Cl:1]"
            match="all_permutations"
```
![Screen Shot 2021-12-21 at 8 51 05 AM](https://user-images.githubusercontent.com/16329175/146968072-dfbb2d27-e762-406b-a17e-7bb0d05c2a4d.png)



```
            type="BondCharge"
            name="EPCl"
            smirks="[*:1][Cl:2]"
            match="all_permutations"
```
![Screen Shot 2021-12-21 at 8 50 24 AM](https://user-images.githubusercontent.com/16329175/146967926-3f447a09-ad9d-421d-b2c1-a312eaaa4223.png)

**Comment by trevorgokey** [comment] 2021-12-21 18:34
Thanks for the report, Jeff. I checked too and agree it's broken. I think transforming the key for the `match=once` case is a mistake.

**Comment by j-wags** [comment] 2021-12-21 19:09
Gotcha. Thanks for the sanity check :-) 

I'm still trying to figure out why that code was there in the first place. Maybe it's to ensure that we get a consistent orientation out for testing purposes? I'm hesitant to remove something until I can explain why it was there in the first place.

The logical error here might be that the code assumes that applying `key_transform` to an orientation doesn't affect the physics of the underlying virtual particle. However, I think that's only true for `TrivalentLonePair`, and (`DivalentLonePair` with an out-of-plane angle of 0). So this bug should also affect `Monovalent` and `DivalentLonePairs`. But we probably never spotted it on those because, conceptually, it only really makes sense to use those with `match="all_permutations"`

I'll open a PR with a new test for this, and we can see whether removing that sorting logic breaks something.

**Comment by trevorgokey** [comment] 2021-12-21 19:28
Yes I agree on all fronts. I was surprised that such a simple example slipped through the existing tests. I think I was hasty in transforming the key since I wanted to keep the "reference" key, but it seems like it was a bad move. It was likely mental carryover from when I was working though `all_permutations`. I think all of my reservations to the change are only valid for `all_permutations`, so I think it should be an OK change. Please let me know if something is off after the change and I can help work through any issues :)

**Closed** 2021-12-22 19:08 UTC
Labels: priority:high

**Comment by SimonBoothroyd** [comment] 2022-01-13 15:45
This seems to fix the regression test failures I have in `openff-recharge` - thanks for this
