### ISSUE TITLE
Error on installation: The following specifications were found to be incompatible with your system:    - feature:/win-64::__cuda==10.2=0

### ISSUE THREAD

**Issue by VicenteMartiCentelles** [openforcefield/openff-toolkit#687] opened 2020-08-25 15:44 UTC
I am getting the following error message when I try to install openforcefield in Windows 10:

```
(base) PS C:\tmp\openmm> conda install openforcefield
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your system:

  - feature:/win-64::__cuda==10.2=0

Your installed version is: 10.2
```

Do you know if the error is from an incompatibility issue in Windows or if there is a way to solve it?

**Comment by j-wags** [comment] 2020-08-25 18:32
Thanks for writing in, @VicenteMartiCentelles,

This looks to be a problem specifically with one of our dependencies, OpenMM. You might try writing to the [issue tracker](https://github.com/openmm/openmm/issues) there. If I had to guess, the issue is that all of the [available OpenMM conda packages](https://anaconda.org/omnia/openmm/files) for Windows are built for CUDA 10.1, whereas your system has CUDA 10.2. Some good news is that it looks like the release candidate packages for the OpenMM 7.5 release do have support for CUDA 10.2, so that may resolve your issue when that release comes out (not sure about the ETA for that, though).

In the short term -- You may be able to manually install CUDA 10.1 to get it to work. 

The OpenFF toolkit in general doesn't currently aim to support Windows, so we can't guarantee that a successful install would necessarily run. If you have the Windows Subsystem for Linux ("WSL"), that has a better chance of being successful.

**Comment by mattwthompson** [comment] 2022-06-17 20:17
This is old so I'm going to close it.

We don't test our stack on Windows and can't make guarantees around compatibility, but there might be workarounds if enough of our dependencies are packaged on Windows (OpenMM, RDKit, and OpenEye all offer Windows packages last I checked).

**Closed by mattwthompson** 2022-06-17 20:17 UTC
