### ISSUE TITLE
validate error when creating ForceField

### ISSUE THREAD

**Issue by jmaat** [openforcefield/openff-toolkit#774] opened 2020-11-25 01:41 UTC
**Describe the bug**
Trying to create forcefield with ForceField(some_force_field_path, allow_cosmetic_attributes=True) results in error (traceback above). This can be remedied by renaming the ChemicalEnvironment.validate() fuction to something else, like validate1 (so maybe some namespace issue regarding the cached_validate()?)

**To Reproduce**
Steps to reproduce the behavior. A minimal reproducing set of python commands is ideal.
ff_path = 'openff-1.3.0.offxml'
forcefield = ForceField(ff_path, allow_cosmetic_attributes=True)

If the problem involves a specific molecule or file, please upload that as well.

**Output**
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in _call_converter(self, value, instance)
    481                 # Static function.
--> 482                 return self._converter(value)
    483             except TypeError:

TypeError: smirks() missing 2 required positional arguments: 'attr' and 'smirks'

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
<ipython-input-4-83eecb13bf3f> in <module>()
      1 ds = ['OpenFF Substituted Phenyl Set 1']
----> 2 makePlots(ds, ff, param_fit, ff_analysis, param_analysis, target_directory)

<ipython-input-2-b250133af74b> in makePlots(ds, ff, param_fit, ff_analysis, param_analysis, target_directory)
     23     sub_dir = [x[0] for x in os.walk(directory) if os.path.basename(x[0]).startswith('td')]
     24 
---> 25     forcefield = ForceField(ff_path, allow_cosmetic_attributes=True)
     26 
     27     #make td Targets

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in __init__(self, aromaticity_model, parameter_handler_classes, parameter_io_handler_classes, disable_version_check, allow_cosmetic_attributes, load_plugins, *sources)
    355 
    356         # Parse all sources containing SMIRNOFF parameter definitions
--> 357         self.parse_sources(sources, allow_cosmetic_attributes=allow_cosmetic_attributes)
    358 
    359     def _initialize(self):

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in parse_sources(self, sources, allow_cosmetic_attributes)
    880             smirnoff_data = self.parse_smirnoff_from_source(source)
    881             self._load_smirnoff_data(
--> 882                 smirnoff_data, allow_cosmetic_attributes=allow_cosmetic_attributes
    883             )
    884 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/forcefield.py in _load_smirnoff_data(self, smirnoff_data, allow_cosmetic_attributes)
   1039             )
   1040             handler._add_parameters(
-> 1041                 parameter_list_dict, allow_cosmetic_attributes=allow_cosmetic_attributes
   1042             )
   1043 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in _add_parameters(self, section_dict, allow_cosmetic_attributes)
   1968                 param_dict = attach_units(unitless_param_dict, attached_units)
   1969                 new_parameter = self._INFOTYPE(
-> 1970                     **param_dict, allow_cosmetic_attributes=allow_cosmetic_attributes
   1971                 )
   1972                 self._parameters.append(new_parameter)

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in __init__(self, smirks, allow_cosmetic_attributes, **kwargs)
   1807         # This is just to make smirks a required positional argument.
   1808         kwargs["smirks"] = smirks
-> 1809         super().__init__(allow_cosmetic_attributes=allow_cosmetic_attributes, **kwargs)
   1810 
   1811     def __repr__(self):

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in __init__(self, allow_cosmetic_attributes, **kwargs)
    907         for key, val in smirnoff_data.items():
    908             if key in allowed_attributes:
--> 909                 setattr(self, key, val)
    910             # Handle all unknown kwargs as cosmetic so we can write them back out
    911             elif allow_cosmetic_attributes:

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in __setattr__(self, key, value)
   1217 
   1218         # Forward the request to the next class in the MRO.
-> 1219         super().__setattr__(key, value)
   1220 
   1221     def add_cosmetic_attribute(self, attr_name, attr_value):

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in __set__(self, instance, value)
    429     def __set__(self, instance, value):
    430         # Convert and validate the value.
--> 431         value = self._convert_and_validate(instance, value)
    432         setattr(instance, self._name, value)
    433 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in _convert_and_validate(self, instance, value)
    447         value = self._validate_units(value)
    448         # Call the custom converter before setting the value.
--> 449         value = self._call_converter(value, instance)
    450         return value
    451 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in _call_converter(self, value, instance)
    483             except TypeError:
    484                 # Instance method.
--> 485                 return self._converter(instance, self, value)
    486         return value
    487 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/engines/smirnoff/parameters.py in smirks(self, attr, smirks)
   1788         # TODO: Add check to make sure we can't make tree non-hierarchical
   1789         #       This would require parameter type knows which ParameterList it belongs to
-> 1790         ChemicalEnvironment.validate_smirks(smirks, validate_valence_type=True)
   1791         return smirks
   1792 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/chemistry/environment.py in validate_smirks(cls, smirks, validate_parsable, validate_valence_type, toolkit_registry)
    189             validate_parsable=validate_parsable,
    190             validate_valence_type=validate_valence_type,
--> 191             toolkit_registry=toolkit_registry,
    192         )
    193 

/Users/jessica/miniconda3/envs/fbruns/lib/python3.7/site-packages/openforcefield/typing/chemistry/environment.py in __init__(self, smirks, label, validate_parsable, validate_valence_type, toolkit_registry)
    116             self.validate(
    117                 validate_valence_type=validate_valence_type,
--> 118                 toolkit_registry=toolkit_registry,
    119             )
    120 

**Computing environment (please complete the following information):**
 - Operating system: MacOS
 - Output of running `conda list` 
# packages in environment at /Users/jessica/miniconda3/envs/fbruns:
#
# Name                    Version                   Build  Channel
abseil-cpp                20200225.2           hb1e8313_2    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
amberlite                 16.0                     pypi_0    pypi
ambertools                20.9                     pypi_0    pypi
appnope                   0.1.0           py37hf985489_1002    conda-forge
argon2-cffi               20.1.0           py37h4b544eb_2    conda-forge
arpack                    3.7.0                hff0ca13_2    conda-forge
arrow-cpp                 2.0.0           py37h63cece2_6_cpu    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
aws-c-common              0.4.59               hc929b4f_1    conda-forge
aws-c-event-stream        0.1.6                hc90cea0_6    conda-forge
aws-checksums             0.1.10               h38ed436_0    conda-forge
aws-sdk-cpp               1.8.70               h154b968_1    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blosc                     1.20.1               hb1e8313_0    conda-forge
bokeh                     2.2.3            py37hf985489_0    conda-forge
boost                     1.72.0           py37hc4fef25_1    conda-forge
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
brotli                    1.0.9                hb1e8313_3    conda-forge
brotlipy                  0.7.0           py37h395d20d_1001    conda-forge
bson                      0.5.9                      py_0    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2020.11.8            h033912b_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
cerberus                  1.3.2                      py_0    conda-forge
certifi                   2020.11.8        py37hf985489_0    conda-forge
cffi                      1.14.4           py37hbddb872_0    conda-forge
cftime                    1.3.0            py37h8ba3199_0    conda-forge
chardet                   3.0.4           py37h2987424_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
clusterutils              0.3.1                    py37_1    omnia
cmiles                    0.1.5                    py37_2    omnia
cryptography              3.2.1            py37h3b7a55b_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.21          py37h08f6e3d_1    conda-forge
cytoolz                   0.11.0           py37h60d8a13_1    conda-forge
dask                      2.30.0                     py_0    conda-forge
dask-core                 2.30.0                     py_0    conda-forge
dask-jobqueue             0.7.1                      py_0    conda-forge
dbus                      1.13.6               h0c50699_1    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.30.1           py37hf985489_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.16             py37h2987424_2    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.2.9                hb1e8313_2    conda-forge
fftw                      3.3.8           nompi_h27769e0_1114    conda-forge
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.1            h6b1039f_1001    conda-forge
forcebalance              1.7.2                    py37_1    omnia
freetype                  2.10.4               h3f75d11_0    conda-forge
fsspec                    0.8.4                      py_0    conda-forge
future                    0.18.2           py37hf985489_2    conda-forge
gettext                   0.19.8.1          haf92f58_1004    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
glib                      2.66.3               h519c658_0    conda-forge
glog                      0.4.0                hb7f4fc5_3    conda-forge
grpc-cpp                  1.33.2               h0202f98_1    conda-forge
h5py                      3.1.0           nompi_py37h6dbf366_100    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_h34ad4e8_1111    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        3.1.0              pyhd8ed1ab_0    conda-forge
importlib_metadata        3.1.0                hd8ed1ab_0    conda-forge
importlib_resources       3.3.0            py37hf985489_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 5.3.4            py37he01cfaa_1    conda-forge
ipython                   5.8.0                    py37_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           5.2.0                    py37_1    conda-forge
jupyter_core              4.7.0            py37hf985489_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kiwisolver                1.3.1            py37h8ec247f_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
latexcodec                2.0.1              pyh9f0ad1d_0    conda-forge
lcms2                     2.11                 h11f7e16_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h4c3b8ed_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               hddc9c9b_3    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               4.0.0               h50e675f_13    conda-forge
libgfortran4              7.5.0               h50e675f_13    conda-forge
libglib                   2.66.3               h2575888_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libnetcdf                 4.7.4           nompi_h4844aed_106    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h63d9170_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libprotobuf               3.13.0.1             hab81aa3_0    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libthrift                 0.13.0               h990abc0_6    conda-forge
libtiff                   4.1.0                hca7d577_6    conda-forge
libutf8proc               2.6.0                hc929b4f_0    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxcb                    1.13              h1de35cc_1002    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.1            py37h091d85b_0    conda-forge
lz4-c                     1.9.2                hb1e8313_3    conda-forge
markupsafe                1.1.1            py37h395d20d_2    conda-forge
matplotlib                3.3.3            py37hf985489_0    conda-forge
matplotlib-base           3.3.3            py37hdacc966_0    conda-forge
mdtraj                    1.9.4            py37h1c7d4b1_2    conda-forge
mistune                   0.8.4           py37h4b544eb_1002    conda-forge
mmpbsa-py                 16.0                     pypi_0    pypi
mock                      4.0.2            py37hc8dfbb8_1    conda-forge
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.3.2                hd33e60e_5    conda-forge
mpiplus                   v0.0.1          py37hc8dfbb8_1002    conda-forge
msgpack-python            1.0.0            py37h6f5c0c7_2    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37hf985489_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
netcdf-fortran            4.5.3           nompi_haced683_101    conda-forge
netcdf4                   1.5.4           nompi_py37h08081e3_103    conda-forge
networkx                  2.5                        py_0    conda-forge
nglview                   2.7.7              pyh5ca1d4c_1    conda-forge
notebook                  6.1.5            py37hf985489_0    conda-forge
numexpr                   2.7.1            py37h6d0141a_3    conda-forge
numpy                     1.19.4           py37h9ebeaaa_1    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openeye-toolkits          2020.1.0                 py37_0    openeye
openff-evaluator          0.2.1              pyh9f0ad1d_0    omnia
openforcefield            0.8.0              pyh39e3cac_0    omnia
openforcefields           1.3.0                      py_0    omnia
openmm                    7.4.2           py37_cuda101_rc_1    omnia
openmmtools               0.20.0                   py37_0    omnia
openmoltools              0.8.7                    py37_0    omnia
openssl                   1.1.1h               haf1e3a3_0    conda-forge
orc                       1.6.5                h4465734_0    conda-forge
oset                      0.1.3                      py_1    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
packmol                   20.010               h43114d0_0    conda-forge
packmol-memgen            1.1.0rc0                 pypi_0    pypi
pandas                    1.1.4            py37h9b0e0a3_0    conda-forge
pandoc                    2.11.2               hc929b4f_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    at20RC5+54.g5702a232fe.dirty          pypi_0    pypi
parquet-cpp               1.5.1                         2    conda-forge
partd                     1.1.0                      py_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pdb4amber                 1.7.dev0                 pypi_0    pypi
pdbfixer                  1.6                        py_1    omnia
perl                      5.32.0               hbcb3906_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py37h09f51b7_0    conda-forge
pint                      0.16.1                     py_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
plotly                    4.13.0             pyhd3deb0d_0    conda-forge
pluggy                    0.13.1           py37h2987424_3    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psutil                    5.7.3            py37h395d20d_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.9.0              pyh9f0ad1d_0    conda-forge
pyarrow                   2.0.0           py37h89d8cab_6_cpu    conda-forge
pybtex                    0.23.0           py37hc8dfbb8_0    conda-forge
pybtex-docutils           0.2.2            py37hc8dfbb8_2    conda-forge
pycairo                   1.20.0           py37ha7df449_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pydantic                  1.7.2            py37h4b544eb_0    conda-forge
pygments                  2.7.2                      py_0    conda-forge
pymbar                    3.0.5            py37h3b54f70_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_4    conda-forge
pyrsistent                0.17.3           py37h4b544eb_1    conda-forge
pysocks                   1.7.1            py37h2987424_2    conda-forge
pytables                  3.6.1            py37he95298d_3    conda-forge
pytest                    6.1.2            py37hf985489_0    conda-forge
python                    3.7.8           h837cb1c_2_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytraj                    2.0.5                    pypi_0    pypi
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1            py37h395d20d_1    conda-forge
pyzmq                     20.0.0           py37h47fd9b3_1    conda-forge
qcelemental               0.17.0                     py_0    conda-forge
qcportal                  0.14.0                     py_1    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
qtconsole                 5.0.0              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
rdkit                     2020.09.1        py37h3dce739_0    conda-forge
re2                       2020.11.01           h2e338ed_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
sander                    16.0                     pypi_0    pypi
scipy                     1.5.3            py37h04d6967_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37h2987424_2    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.19.8           py37h0a44026_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smirnoff99frosst          1.1.0                    py37_1    omnia
snappy                    1.1.8                hb1e8313_3    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sphinx                    3.3.1              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.33.0               h960bd1c_1    conda-forge
swig                      4.0.2                h4a8c4bd_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.9.1            py37hf985489_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hb0a8c7a_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py37h4b544eb_0    conda-forge
tqdm                      4.53.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
uncertainties             3.1.5              pyhd8ed1ab_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
widgetsnbextension        3.5.1            py37hf985489_4    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-kbproto              1.0.7             h1de35cc_1002    conda-forge
xorg-libice               1.0.10               h01d97ff_0    conda-forge
xorg-libsm                1.2.3             h01d97ff_1000    conda-forge
xorg-libx11               1.6.12               haf1e3a3_0    conda-forge
xorg-libxau               1.0.9                h1de35cc_0    conda-forge
xorg-libxdmcp             1.1.3                h01d97ff_0    conda-forge
xorg-libxext              1.3.4                h01d97ff_0    conda-forge
xorg-libxt                1.2.0                h01d97ff_0    conda-forge
xorg-xextproto            7.3.0             h1de35cc_1002    conda-forge
xorg-xproto               7.0.31            h1de35cc_1007    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yank                      0.25.2                   py37_1    omnia
zeromq                    4.3.3                h74dc148_3    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.5                h289c70a_2    conda-forge

**Additional context**

**Comment by j-wags** [comment] 2020-11-25 02:40
Hm, could you upload the `offxml` file that it's having trouble loading? I have two thoughts:
* Is this workflow trying to load a local file? If there's a file in the current directory called `openff-1.3.0.offxml`, the toolkit may preferentially load than instead of the `openff-1.3.0.offxml` from the `openforcefields` package. In general, I think the current toolkit behavior will be confusing if files are named the same as files provided by the `openforcefields` package. 
* This error may actually be informative -- It would indicate that there's a SMIRKS that doesn't have the right number of tagged atoms, or tagged atoms that aren't connected in the expected way.

**Comment by jmaat** [comment] 2020-11-30 16:25
> Hm, could you upload the offxml file that it's having trouble loading? I have two thoughts:

I downloaded the 1.3.0 FF directly from this page - https://github.com/openforcefield/openforcefields/blob/master/openforcefields/offxml/openff-1.3.0.offxml 

> Is this workflow trying to load a local file?
It could be but I also placed the 1.3.0 .offxml in the local directory so it should be loading the same file in either case

**Comment by j-wags** [comment] 2020-12-02 14:40
We worked together on this yesterday using a fresh conda environment and were unable to reproduce the original error. I'll close this issue for now, but we can reopen it and investigate further if it pops up again.

**Closed** 2021-12-07 22:27 UTC
