### ISSUE TITLE
Allow Molecule.from_file() to optionally read in specified molecules

### ISSUE THREAD

**Issue by jchodera** [openforcefield/openff-toolkit#446] opened 2019-10-29 02:12 UTC
**Is your feature request related to a problem? Please describe.**
[`Molecule.from_file()`](https://open-forcefield-toolkit.readthedocs.io/en/0.5.1/api/generated/openforcefield.topology.Molecule.html#openforcefield.topology.Molecule.from_file) can read a file containing multiple molecules. Currently, it will read _all_ molecules from the file, which may not be needed. 
```python
>>> mols = Molecule.from_file('MiniDrugBank.sdf', allow_undefined_stereo=True)
>>> len(mols)
371
```

**Describe the solution you'd like**
We could add an optional `molecule_indices` argument that would optionally specify _which_ molecules should be read, such as
```python
# Read only the first molecule
>>> mol = Molecule.from_file('MiniDrugBank.sdf', molecule_indices=0, allow_undefined_stereo=True)
# Read only the first five molecules
>>> mols = Molecule.from_file('MiniDrugBank.sdf', molecule_indices=range(5), allow_undefined_stereo=True)
# Read specific molecules
>>> mols = Molecule.from_file('MiniDrugBank.sdf', molecule_indices=[1,37,200], allow_undefined_stereo=True)
```

**Describe alternatives you've considered**
There appear to be no alternatives other than using toolkits directly, which breaks toolkit independence.

**Additional context**
This would be very useful for testing purposes.

**Comment by mattwthompson** [comment] 2023-02-01 17:08
Related #854

**Comment by mattwthompson** [comment] 2023-02-01 19:15
Duplicate of https://github.com/openforcefield/openff-toolkit/issues/282

**Closed by mattwthompson** 2023-02-01 19:15 UTC
